name: michaelianelias.net
favicon: null
layout_spectrum: 0.30329718021675944
typography_spectrum: 0.4119679811410606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6643127887509763
  lightness: 0.562058957060799
  saturation: 0.07939491025172174
  rhythmicContrast: 0.5830093317199498
purpose: []
